### PR TITLE
Add a Powershell cmdlet.

### PR DESCRIPTION
**Pull request by chrisguest75**
Hi, It's my first time using github so please feel free to direct me to a better of handling this type of change.  I notice that your library uses mono rather than being a Windows only project.  Obviously Powershell is Windows only.  That's why I've create a new solution that references the projects of your one and adds an InfluxDBPS project as well. 

As I say I'm new to all this and don't really fully understand the options open to me when referencing other people's projects to build my own.  I suppose one option is that we create a nuget package and then I could reference that in my solution/project.  

Thoughts?  

Chris.

### CODE REVIEW

**Comment by chrisguest75** [comment]
Hi ziyasal,
   I see you're adding InfluxDB.Net to nuget.  You mention in the comments that there is already another fork with the same name - I assume you're implying mine.  If you're adding to nuget I'll destroy my fork and create an new project that will wrap your library for Powershell.  I'll call mine InfluxDBPS or something similar.

Please share your thoughts. 

Chris

**Comment by ziyasal** [comment]
Hi @chrisguest75,

Thanks for your contributions. There is  [another package](https://www.nuget.org/packages/InfluxDB.NET) not yours :) I think, PS project can be part of project. Web can create another package for PS. Also, this is PCL package and available for mono and .net. I will merge pull request after review.

**Comment by ziyasal** [comment]
Hi @chrisguest75, 
To use InfluxDB from PowerShell documentation would be nice. Can you add sample usage to readme?

**Comment by chrisguest75** [comment]
Hi @ziyasal,
I'll add some documentation ASAP. For the time being there is an example PS script that demonstrates a simple usage of it.  I'll need to pull the code back to my fork patch things up and push it back to you first.  Thanks for accommodating my updates. 

Chris.

**Comment by chrisguest75** [comment]
Hi @ziyasal,
Where would you like me to add the documentation?  I think if I add it to the readme it would be confusing.  Is it possible to add multiple readme's?

Chris

**Comment by ziyasal** [comment]
Hi @chrisguest75 You right, according to me; create new wiki page and reference its url in readme.md.

**Comment by chrisguest75** [comment]
Ok thanks.  I've also got some more changes I'll create a pull request for.  I've synced your changes and merged.  Just starting to get used git. :-)

**Comment by ziyasal** [comment]
Hi @chrisguest75 Good to hear that :) Thanks.

**Pull request merged**
